# versão do docker
version: '3'
# serviços
services:
  # serviço do sistema
  sistema:
    # builda a imagem do docker
    build: ./
    # variáveis de ambiente
    # env_file: ./.env
    # portas em que o serviço está rodando
    ports:
      - '80:80'
    # volume disponível
    volumes:
      - ./:/var/www/localhost.com.br/public_html/
  